export enum Icons {
  ARROW_DOWN = 'arrow-down',
  ARROW_EXPAND = 'arrow-expand',
  ARROW_RIGHT = 'arrow-right',
  ARROW_UP = 'arrow-up',
  BEHANCE = 'behance',
  CERTIFICATE = 'certificate',
  CROSS = 'cross',
  FIGMA = 'figma',
  GITHUB = 'github',
  IDEA = 'idea',
  LINKEDIN = 'linkedin',
  LOCATION = 'location',
  MAIL = 'mail',
  MENU = 'menu',
  OFFICE_BAG = 'office-bag',
  STUDY = 'study',
  WHATSAPP = 'whatsapp',
}
